Repository Radio-Premium/RadioPremium-FE, pull requests merged in 2025-05, with the labels that each got.

#2 chore: 프론트엔드 프로젝트 초기 세팅
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  commitlint.config.cjs
  eslint.config.js
  index.html
  package.json
  src/App.jsx
  src/index.css
  src/layout/MainLayout.jsx
  src/main.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
  src/pages/Settings.jsx
  src/routes/index.jsx
  vite.config.js
Labels: ⚙️setting

#9 feat: 토글 버튼 컴포넌트 UI 구현
  src/components/ToggleButton.jsx
Labels: ✨feat

#12 feat: 하단 미니 플레이어 UI 구현
  src/assets/svgs/CloseIcon.svg
  src/assets/svgs/PauseIcon.svg
  src/assets/svgs/PlayIcon.svg
  src/components/MiniPlayer.jsx
Labels: ✨feat

#11 feat: 광고 제보 모달 UI 구현
  src/assets/svgs/icon-warning-red.svg
  src/components/AdReportModal.jsx
  src/components/ToggleCheckbox.jsx
  src/components/ui/Button.jsx
  src/components/ui/Checkbox.jsx
  src/components/ui/Modal.jsx
Labels: ✨feat

#25 chore: Zustand 설치
  package.json
Labels: 💡chore

#27 feat: 검색 화면 페이지 구현
  src/components/ChannelListItem.jsx
  src/components/header/RadioSearchInput.jsx
  src/pages/Search.jsx
Labels: ✨feat
