Repository Radio-Premium/RadioPremium-FE, pull requests merged in 2025-06, with the labels that each got.

#32 feat: TabBar에서 Setting 탭 클릭 시 경로 이동 기능 추가
  src/components/TabBar.jsx
Labels: ✨feat

#35 chore: socket.io-client 설치
  package.json
Labels: ⚙️setting

#37 feat: Client 소켓 연결 작업
  src/hooks/useAdKeywordsSocketListener.jsx
  src/sockets/socketClient.js
Labels: ✨feat

#30 style: UI 스타일 정리 및 아이콘 파일명 변경
  src/assets/svgs/icon-close.svg
  src/assets/svgs/icon-mini-pause.svg
  src/assets/svgs/icon-mini-play.svg
  src/assets/svgs/icon-radio-premium-logo.svg
  src/assets/svgs/icon-search-bold.svg
  src/components/AdReportModal.jsx
  src/components/ChannelListItem.jsx
  src/components/MiniPlayer.jsx
  src/components/ToggleCheckbox.jsx
  src/components/header/MainHeader.jsx
  src/components/ui/Modal.jsx
  src/pages/Search.jsx
Labels: ⭕rename, 🎨style

#48 chore: axios 설치
  package.json
Labels: ⚙️setting

#49 feat: 신규 사용자 등록 API 연동
  src/hooks/useUserId.jsx
  src/pages/Home.jsx
Labels: ✨feat, 🖥️api

#53 feat: 라디오 채널 목록 조회 API 연동
  .gitignore
  src/hooks/useChannels.jsx
  src/pages/Home.jsx
  src/store/useChannelStore.js
Labels: ✨feat, 🖥️api

#55 feat: 라디오 채널 정보 조회 API 연동
  src/components/ChannelListItem.jsx
  src/components/FavoriteChannelListItem.jsx
  src/hooks/useChannelInfo.jsx
  src/hooks/useChannelNavigation.jsx
  src/hooks/useChannelSwitch.jsx
  src/pages/ChannelPlayer.jsx
  src/pages/Home.jsx
  src/routes/index.jsx
  src/store/useChannelStore.js
  src/utils/playControl.js
Labels: ✨feat, 🖥️api

#56 feat: 관심 채널 분리를 위한 Zustand 상태 및 커스텀 훅 로직 추가
  src/hooks/useCategorizeChannel.jsx
  src/hooks/useCategorizeChannels.jsx
  src/hooks/useInterestChannels.jsx
  src/pages/Home.jsx
  src/store/useChannelStore.js
Labels: ✨feat, 🖥️api

#62 feat: 관심 채널 등록, 삭제, 수정 API 연동
  src/apis/axiosInstance.js
  src/apis/interestChannels.js
  src/components/ChannelListItem.jsx
  src/components/FavoriteChannelList.jsx
  src/components/FavoriteChannelListItem.jsx
  src/hooks/useToggleFavorite.jsx
  src/pages/Home.jsx
  src/utils/dragHandlers.js
Labels: ✨feat, 🖥️api

#64 chore: tanstack query 설치
  eslint.config.js
  package-lock.json
  package.json
  src/App.jsx
Labels: 💡chore

#67 fix: Cannot destructure property 'name' of 'useChannelInfo(...)' as it is null 문제 해결
  src/pages/ChannelPlayer.jsx
Labels: 🐞bug, 🔧fix, 🚨hotfix

#70 refactor: 사용자 정보 조회 로직 통합
  src/hooks/useUserData.jsx
  src/hooks/useUserProfile.jsx
  src/pages/Home.jsx
  src/pages/Settings.jsx
Labels: 🛠️refactor

#71 refactor: 플레이 버튼 클릭 시 사용자 정보 조회 API 연동하도록 동작 변경
  src/apis/radioChannels.js
  src/hooks/useChannelInfo.jsx
  src/pages/ChannelPlayer.jsx
  src/store/useChannelStore.js
  src/utils/playControl.js
Labels: 🛠️refactor

#78 refactor: 광고 감지 여부에 따른 whisper 서버 연결
  src/apis/radioChannels.js
  src/components/MiniPlayer.jsx
  src/hooks/useChannelPlayback.jsx
  src/pages/ChannelPlayer.jsx
  src/utils/playControl.js
Labels: 🛠️refactor

#81 fix: 'settings' is not defined. 문제 해결
  src/pages/ChannelPlayer.jsx
Labels: 🐞bug, 🔧fix, 🚨hotfix

#83 feat: 검색 기능 구현
  src/components/SearchResultListItem.jsx
  src/components/header/RadioSearchInput.jsx
  src/pages/Search.jsx
  src/store/useSearchStore.js
Labels: ✨feat

#87 feat: 광고 감지 기반 스트리밍 소스 교체 기능 추가 및 관련 로직 리팩토링
  src/hooks/useAdKeywordsSocketListener.jsx
  src/hooks/useChannelPlayback.jsx
  src/hooks/useChannelSwitch.jsx
  src/pages/ChannelPlayer.jsx
  src/utils/playControl.js
Labels: ✨feat, 🛠️refactor

#90 fix: 관심 채널 즐겨찾기 등록 및 정렬 동작 개선
  src/hooks/useCategorizeChannels.jsx
  src/hooks/useToggleFavorite.jsx
Labels: 🔧fix

#93 feat: 소켓 연결 시 사용자 ID 전달 로직 구현
  src/apis/radioChannels.js
  src/hooks/useAdKeywordsSocketListener.jsx
  src/utils/playControl.js
Labels: ✨feat

#94 feat: MiniPlayer 연동
  src/components/MiniPlayer.jsx
  src/hooks/useChannelPlayback.jsx
  src/layout/MainLayout.jsx
  src/pages/ChannelPlayer.jsx
  src/store/useChannelStore.js
  src/store/useMiniPlayerStore.js
  src/store/usePlayingStore.js
  src/utils/playControl.js
  src/utils/videoElement.js
Labels: ✨feat

#97 style: 스타일 수정 [채널 간 간격 · 섹션 마진 · 텍스트 정렬 개선]
  src/components/ChannelSection.jsx
  src/components/SettingListItem.jsx
  src/components/ui/ToggleButton.jsx
  src/constants/settingOptions.js
  src/pages/Home.jsx
Labels: 🎨style

#100 feat: 광고 감지 시 플레이어 채널 정보 변경
  src/hooks/useChannelSwitch.jsx
  src/hooks/useControlStreamingSwitch.jsx
  src/pages/ChannelPlayer.jsx
  src/store/useChannelStore.js
  src/store/useMiniPlayerStore.js
  src/utils/playControl.js
Labels: ✨feat

#101 chore: vitest 테스트 환경 초기 세팅
  package-lock.json
  package.json
  vite.config.js
Labels: 💡chore

#103 fix: 사용자가 채널 이동할 때 isChannelChanged 초기화
  src/hooks/useChannelNavigation.jsx
Labels: 🔧fix

#107 fix: 사용자 재생 요청 채널에만 Whisper 서버 호출되도록 로직 개선
  src/apis/radioChannels.js
  src/hooks/useControlStreamingSwitch.jsx
  src/utils/playControl.js
Labels: 🔧fix

#109 fix: 광고 감지 후 사용자 채널 복귀 로직 오류 수정
  src/hooks/useChannelSwitch.jsx
Labels: 🔧fix

#113 feat: MiniPlayer 종료 시 Whisper 서버 중단 처리 추가
  src/components/MiniPlayer.jsx
  src/utils/playControl.js
  src/utils/stopWhisperServer.js
Labels: ✨feat

#119 refactor: 광고 감지 로직 전역화 및 video 엘리먼트 전역 상태 관리로 전환
  src/App.jsx
  src/components/MiniPlayer.jsx
  src/hooks/useAdKeywordsSocketListener.jsx
  src/hooks/useChannelPlayback.jsx
  src/hooks/useChannelSwitch.jsx
  src/hooks/useControlStreamingSwitch.jsx
  src/layout/MainLayout.jsx
  src/pages/ChannelPlayer.jsx
  src/store/useVideoElementStore.js
  src/utils/videoElement.js
Labels: 🛠️refactor

#121 feat: 미니 플레이어 클릭 시 채널 플레이어로 이동 기능 구현
  src/components/MiniPlayer.jsx
  src/hooks/useChannelPlayback.jsx
Labels: ✨feat

#129 feat: 광고 감지 시 이동할 채널 선택 API 연동
  src/constants/settingOptions.js
  src/hooks/useUpdateSetting.jsx
  src/hooks/useUserProfile.jsx
  src/pages/Settings.jsx
  src/store/useUserStore.js
Labels: ✨feat

#133 feat: 광고 감지 시 이동할 채널 선택에 따른 채널 이동 기능 구현
  src/hooks/useChannelSwitch.jsx
Labels: ✨feat

#139 feat: 파비콘(favicon.ico) 추가 및 브라우저 탭 아이콘 설정
  index.html
  public/favicon.ico
Labels: ✨feat

#154 refactor: 스토어 네이밍 명확화 및 import 경로 수정
  src/Channel/hooks/useChannelSwitch.jsx
  src/Playback/__tests__/Playback.test.jsx
  src/Playback/components/ChannelPlayer.jsx
  src/Playback/hooks/useChannelPlayback.jsx
  src/User/__tests__/Settings.test.jsx
  src/User/components/SettingListItem.jsx
  src/User/components/Settings.jsx
  src/User/hooks/useUpdateSetting.jsx
  src/User/hooks/useUserProfile.jsx
  src/User/stores/useUserSettingsStore.js
Labels: 🛠️refactor

#163 refactor: Zustand 상태 업데이트 네이밍 및 함수 작성 스타일 통일
  src/Channel/hooks/useChannelSwitch.jsx
  src/Channel/stores/useChannelStore.js
  src/Playback/__tests__/Playback.test.jsx
  src/Playback/components/ChannelPlayer.jsx
  src/Playback/hooks/useChannelPlayback.jsx
  src/Playback/stores/useMiniPlayerStore.js
  src/Playback/stores/usePlayingStore.js
  src/Search/stores/useSearchStore.js
  src/User/__tests__/Settings.test.jsx
  src/User/components/SettingListItem.jsx
  src/User/components/Settings.jsx
  src/User/hooks/useUpdateSetting.jsx
  src/User/stores/useUserSettingsStore.js
Labels: 🛠️refactor
